### ISSUE TITLE
client/client.py 에러

### ISSUE THREAD

**Issue by GyuYoungLee** [freelec/gke-gobang-app-example#1]
올해 4월 쯤에는 실행되었는데요. 책 다시 보다가 해보니 지금은 코드 동작 안합니다. 

```
abc123@cloudshell:~/gke-gobang-app-example (first-217912)$ docker container ls
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
516b0b6e7ed1        frontend:v1.0       "/opt/gobang/bin/fro…"   6 seconds ago       Up 5 seconds        0.0.0.0:8080->8080/tcp   frontend
e5b81042bb0b        backend:v1.0        "/opt/gobang/bin/bac…"   14 seconds ago      Up 13 seconds       8081/tcp                 backend
abc123@cloudshell:~/gke-gobang-app-example (first-217912)$ API_URL=http://localhost:8080/api/v1 client/client.py
Welcome to Gobang (Five in a Row) game.
Game ID (0:new game)?
Bad input.
Game ID (0:new game)? 0
Traceback (most recent call last):
  File "client/client.py", line 71, in <module>
    id = new_game()
  File "client/client.py", line 27, in new_game
    return response.json()['id']
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by leechungkyu** [comment]
동일한 에러 발생되어 동작하지 않고 있습니다. 책 248 page

`root@docker:/k8s/gke-gobang-app-example.bk# API_URL=http://34.85.10.223/api/vi client/client.py
Welcome to Gobang (Five in a Row) game.
Game ID (0:new game)? 5629499534213120
Traceback (most recent call last):
  File "client/client.py", line 76, in <module>
    board = get_board(id)
  File "client/client.py", line 37, in get_board
    return response.json()['board']
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`
